### ISSUE TITLE
Press tab does not move horizontal scrollbar

### ISSUE THREAD

**Issue by ArunPatal** [ukandrewc/Ace-Scrollbars#1]
Hello,

Pressing any key do move the scrollbar but pressing tab does not move the scrollbar until any other key is pressed...

**Comment by ukandrewc** [comment]
Tab doesn't control the scrollbar, can you explain what you mean please.

**Comment by ArunPatal** [comment]
![scrollbar](https://user-images.githubusercontent.com/30784805/116230603-78861f00-a775-11eb-818e-105f99ed5e3d.png)

Please check the image above.
Adding tab space increase space as scrollbar is getting smaller but scrollbar is not moving automatically..
It moves to cursor position only when any other key is pressed.

**Comment by ukandrewc** [comment]
That's an Ace issue, it does the same with normal scrollbars.
